/**
 * IMPT Google Ads — Daily Performance Report Script
 *
 * Purpose: Sends a daily email report of campaign performance.
 *          Run every morning to know exactly what yesterday cost
 *          and what it converted.
 *
 * HOW TO USE:
 * 1. In Google Ads → Tools → Scripts → + New Script
 * 2. Paste this entire file
 * 3. Set REPORT_EMAIL to your email address
 * 4. Set frequency to "Daily" at 7:00am your timezone
 * 5. Authorise and run
 */

var REPORT_EMAIL   = 'your@email.com';  // Replace with your email
var CAMPAIGN_LABEL = 'IMPT';

function main() {
  var yesterday = getYesterdayDateRange();
  var last7days  = getLookbackDateRange(7);
  var last30days = getLookbackDateRange(30);

  var yesterdayData = getCampaignData(yesterday);
  var last7Data     = getCampaignData(last7days);
  var last30Data    = getCampaignData(last30days);

  var subject = 'IMPT Google Ads Report — ' + Utilities.formatDate(
    new Date(), AdsApp.currentAccount().getTimeZone(), 'dd MMM yyyy'
  );

  var body = buildEmailBody(yesterdayData, last7Data, last30Data);

  MailApp.sendEmail(REPORT_EMAIL, subject, '', {htmlBody: body});
  Logger.log('Report sent to ' + REPORT_EMAIL);
}

function getCampaignData(dateRange) {
  var report = AdsApp.report(
    'SELECT CampaignName, Impressions, Clicks, Cost, Conversions, Ctr, AverageCpc, ConversionRate ' +
    'FROM CAMPAIGN_PERFORMANCE_REPORT ' +
    'WHERE LabelNames CONTAINS_ANY ["' + CAMPAIGN_LABEL + '"] ' +
    'DURING ' + dateRange
  );

  var campaigns = [];
  var totals = {impressions: 0, clicks: 0, cost: 0, conversions: 0};
  var rows = report.rows();

  while (rows.hasNext()) {
    var row = rows.next();
    var clicks      = parseInt(row['Clicks']);
    var cost        = parseFloat(row['Cost']);
    var conversions = parseFloat(row['Conversions']);

    campaigns.push({
      name:        row['CampaignName'],
      impressions: parseInt(row['Impressions']),
      clicks:      clicks,
      cost:        cost,
      conversions: conversions,
      ctr:         row['Ctr'],
      avgCpc:      row['AverageCpc'],
      cpa:         conversions > 0 ? (cost / conversions).toFixed(2) : 'N/A',
    });

    totals.impressions += parseInt(row['Impressions']);
    totals.clicks      += clicks;
    totals.cost        += cost;
    totals.conversions += conversions;
  }

  totals.cpa = totals.conversions > 0
    ? '€' + (totals.cost / totals.conversions).toFixed(2)
    : 'N/A';
  totals.ctr = totals.impressions > 0
    ? ((totals.clicks / totals.impressions) * 100).toFixed(2) + '%'
    : '0%';

  return {campaigns: campaigns, totals: totals};
}

function buildEmailBody(yesterday, last7, last30) {
  var html = '<html><body style="font-family:Arial,sans-serif;color:#333;">';
  html += '<h2 style="color:#1a73e8;">IMPT Google Ads — Daily Report</h2>';

  html += buildSection('Yesterday', yesterday);
  html += buildSection('Last 7 Days', last7);
  html += buildSection('Last 30 Days', last30);

  html += '<p style="color:#999;font-size:12px;">Generated by IMPT Ads Script</p>';
  html += '</body></html>';
  return html;
}

function buildSection(label, data) {
  var t = data.totals;
  var html = '<h3>' + label + '</h3>';
  html += '<table border="1" cellpadding="6" cellspacing="0" style="border-collapse:collapse;width:100%;">';
  html += '<tr style="background:#1a73e8;color:white;">';
  html += '<th>Campaign</th><th>Impressions</th><th>Clicks</th><th>CTR</th><th>Avg CPC</th><th>Cost</th><th>Conversions</th><th>CPA</th>';
  html += '</tr>';

  for (var i = 0; i < data.campaigns.length; i++) {
    var c = data.campaigns[i];
    var cpaColor = c.cpa === 'N/A' ? '#999' : parseFloat(c.cpa) > 10 ? 'red' : 'green';
    html += '<tr>';
    html += '<td>' + c.name + '</td>';
    html += '<td>' + c.impressions.toLocaleString() + '</td>';
    html += '<td>' + c.clicks + '</td>';
    html += '<td>' + c.ctr + '</td>';
    html += '<td>€' + parseFloat(c.avgCpc).toFixed(2) + '</td>';
    html += '<td>€' + c.cost.toFixed(2) + '</td>';
    html += '<td>' + c.conversions + '</td>';
    html += '<td style="color:' + cpaColor + ';">€' + c.cpa + '</td>';
    html += '</tr>';
  }

  html += '<tr style="font-weight:bold;background:#f5f5f5;">';
  html += '<td>TOTAL</td>';
  html += '<td>' + t.impressions.toLocaleString() + '</td>';
  html += '<td>' + t.clicks + '</td>';
  html += '<td>' + t.ctr + '</td>';
  html += '<td>—</td>';
  html += '<td>€' + t.cost.toFixed(2) + '</td>';
  html += '<td>' + t.conversions + '</td>';
  html += '<td>' + t.cpa + '</td>';
  html += '</tr>';
  html += '</table><br/>';
  return html;
}

function getYesterdayDateRange() {
  var d = new Date();
  d.setDate(d.getDate() - 1);
  var s = Utilities.formatDate(d, AdsApp.currentAccount().getTimeZone(), 'yyyyMMdd');
  return s + ',' + s;
}

function getLookbackDateRange(days) {
  var end = new Date();
  end.setDate(end.getDate() - 1);
  var start = new Date();
  start.setDate(start.getDate() - days);
  var tz = AdsApp.currentAccount().getTimeZone();
  return Utilities.formatDate(start, tz, 'yyyyMMdd') +
    ',' +
    Utilities.formatDate(end, tz, 'yyyyMMdd');
}
